config/routes.rb
Rails.application.routes.draw do

  get 'tags/index'

  get 'home/dashboard' => 'home#dashboard'
  root 'home#dashboard'

  get '/get_favourites' => 'home#get_favs'
  get '/get_toppers' => 'home#get_toppers'
  post '/get_search' => 'home#get_search'
  get '/make_favourite' => 'home#make_favourite'
  get '/make_rating' => 'home#make_rating'

  get '/categories/:id' => 'categories#show', :as => :show_category, :id=>/\d+/

  post '/categories/create' => 'categories#create', :as => :create_category
  post '/categories/update' => 'categories#update', :as => :update_category

  get '/sub-categories/:id' => 'sub_categories#show', :as => :show_sub_category, :id=>/\d+/

  post '/sub-categories/create' => 'sub_categories#create', :as => :create_sub_category
  post '/sub-categories/update' => 'sub_categories#update', :as => :update_sub_category

  get '/articles/:id' => 'articles#show', :as => :show_article, :id=>/\d+/

  post '/articles/create' => 'articles#create', :as => :create_article
  post '/articles/update' => 'articles#update', :as => :update_article

  get '/tags/:id' => 'tags#show', :as => :show_tag, :id=>/\d+/

  post '/tags/create' => 'tags#create', :as => :create_tag
  post '/tags/update' => 'tags#update', :as => :update_tag

  resources :articles, :categories, :sub_categories, :tags

  get ':id' => 'home#tiny_url', :article_id => /\d+/, :as => :tiny_url

end

app/models/article.rb
class Article < ActiveRecord::Base

  class << self
    include ApplicationHelper
  end

  belongs_to :user
  belongs_to :sub_category
  has_many :comments
  has_and_belongs_to_many :tags

  validates :title, presence: true
  validates :description, presence: true
  validates :content, presence: true

  scope :by_active, -> {where('status = ?', true)}
  scope :by_favs, -> {where('favourite = ?', true)}
  scope :latest_by_updated, -> { order("updated_at desc") }
  scope :top_rated, -> { order("rating desc") }

  before_save :content_replace

  def content_replace
    self.content=self.content.gsub('<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ','<p class="three">')
    self.content=self.content.gsub('<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ','<p class="two">')
    self.content=self.content.gsub('<p>&nbsp;&nbsp; ','<p class="one">')
  end

  def category
    self.sub_category.category
  end

  def self.get_favourites
    fetch_values(Article.by_favs.first(6), "url_helpers.show_article_path(y.id)")
  end

  def self.get_toppers
    fetch_values(Article.top_rated.first(6), "url_helpers.show_article_path(y.id)")
  end

  def self.get_search(value)
    article=Article.where("title LIKE ? or description LIKE ? OR content LIKE ?", "%#{value}%", "%#{value}%", "%#{value}%").uniq
    fetch_values(article, "url_helpers.show_article_path(y.id)")
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def new
    @page_properties.merge!({:header => "New Article"})
    @article = Article.new
  end

  def edit
    @page_properties.merge!({:header => "Edit Article"})
    @article = Article.find(params[:id])
  end

  def index
    @page_properties.merge!({:header => "Articles"})
    @articles = Article.all.order(rating: :desc)
  end

  def show
    @article = Article.find(params[:id])
    @page_properties.merge!({:header => @article.title})
  end

  def create
    article_params[:tag_ids] ||= params[:tag_ids]
    @article = Article.new(article_params)
    if @article.save
      redirect_to articles_path
    else
      render 'new'
    end
  end

  def update
    @article = Article.find(params[:id])
    article_params[:tag_ids] ||= params[:tag_ids]
    if @article.update(article_params)
      redirect_to articles_path
    else
      render 'edit'
    end
  end

  def destroy
    @sub_category = SubCategory.find(params[:sub_category_id])
  end

  private

  def article_params
    params.require(:article).permit(:title, :description, :content, :status, :reference_url, :github_url, :rating, :sub_category_id, :tag_ids=>[])
  end

end

app/views/articles/_articles_block.html.erb
<%if @articles.present?%>
    <div class="index" align="center">
      <% @articles.each do |a| %>
          <a href="<%= show_article_path(a.id) %>">
            <div class="article">
              <div class="head">
                <div class="title">
                  <h3><%= a.title %></h3>
                  <h6><%= a.description %></h6>
                </div>
                <div class="count">
          <span>
            <%= a.rating%>
          </span>
                  <p><%= a.rating!=1 ? "Stars".pluralize : "Stars".singularize %></p>
                </div>
              </div>
            </div>
          </a>
      <% end %>
    </div>
<%else%>
    <div class="index" align="center">
      <h4>No Data to Display</h4>
    </div>
<%end%>

app/views/articles/_form.html.erb
<div class="wrapper">
  <div class="heading">
    <h3><%= @page_properties[:header]%></h3>
  </div>

  <% @breadcrumb = {:Home => root_path, :Article => articles_path }%>
  <% @article.new_record? ? (@breadcrumb[:New] = "#") : (@breadcrumb[@article.title] = show_article_path(@article.id);@breadcrumb[:Edit] = "#") %>
  <%= render :partial => 'layouts/bread_crumb' %>

  <%= form_for @article, method: :post, :url => @article.new_record? ? :create_article : :update_article do |f| %>
      <div class="form_container_right">

        <div class="form_element">
          <%= f.label :title %>
          <%= f.text_field :title, class: 'form_field' %>
        </div>

        <div class="form_element">
          <%= f.label :description %>
          <%= f.text_field :description, class: 'form_field' %>
        </div>

        <div class="form_element">
          <%= f.label :sub_category%>
          <%= collection_select :article, :sub_category_id, SubCategory.all, :id, :name, options={:selected => @article.sub_category.try(:id), :include_blank => '--Select Sub Category--'}, {:class=>"cs-select cs-skin-elastic"} %>
        </div>

        <div class="form_element">
          <%= f.label :reference_url %>
          <%= f.text_field :reference_url, class: 'form_field' %>
        </div>

        <div class="form_element">
          <%= f.label :github_url %>
          <%= f.text_field :github_url, class: 'form_field' %>
        </div>

        <div class="form_element">
          <%= f.label :tags%>
          <%#= hidden_field "tag_ids", nil, :value => nil %>
          <%= raw custom_autocomplete("article[tag_ids]", Tag.all, "name", @article.tags) %>
        </div>
      </div>

      <div class="form_container_left">
        <%= f.label :content %>
        <%#= f.text_area :content, class: 'form_content' %>
        <%= f.text_area :content, class: "tinymce form_content" %>
      </div>

      <%= hidden_field_tag :id, params[:id] %>

      <div class="form_container_bottom" align="center">
        <%= custom_submit_1("submit") %>
      </div>
  <% end %>
  <!-- Go to www.addthis.com/dashboard to customize your tools -->

  <% @mandatory_field = ['title','description','content'].to_json %>
  <% @attach_field = ['article_'].to_json %>
  <%= render :partial => 'layouts/jquery_validation' %>

  <%= tinymce :plugins => ["wordcount", "paste", "preview", "code", "table"] %>
</div>

app/views/articles/index.html.erb
<div class="wrapper">
  <div class="heading">
    <h3><%= @page_properties[:header]%></h3>
    <%= custom_button_1("New Article", new_article_path, "right") %>
  </div>

  <% @breadcrumb ={:Home => root_path, :Articles => "#"} %>
  <%= render :partial => 'layouts/bread_crumb'%>

  <%= render :partial => 'articles/articles_block' %>
</div>

app/views/articles/new.html.erb
<%= render 'form' %>

app/views/articles/show.html.erb
<div class="wrapper">
  <div class="heading">
    <h3><%= @page_properties[:header] %></h3>

    <div class="fav <%= @article.favourite ? "already-fav" : "make-fav" %>" data-url="Article" data-id="<%= @article.id %>"></div>

    <%= custom_button_2("Edit Article", edit_article_path(@article.id), "right") %>

    <div class="rating" id="<%= @article.id %>">
      <%= raw custom_rating_1(@article.rating) %>
    </div>

  </div>
  <% @breadcrumb ={:Home => root_path, :Categories => categories_path, @article.category.name => show_category_path(@article.category.id), @article.sub_category.name => show_sub_category_path(@article.sub_category_id), @article.title => "#"} %>
  <%= render :partial => 'layouts/bread_crumb' %>

  <div class="article-content">
    <div class="description">
      <%= @article.description %>
    </div>

    <div class="content">
      <%= raw @article.content %>
    </div>
  </div>
</div>