config/routes.rb
Rails.application.routes.draw do

  get 'tags/index'

  get 'home/dashboard' => 'home#dashboard'
  root 'home#dashboard'

  get '/get_favourites' => 'home#get_favs'
  get '/get_toppers' => 'home#get_toppers'
  post '/get_search' => 'home#get_search'
  get '/make_favourite' => 'home#make_favourite'
  get '/make_rating' => 'home#make_rating'

  get '/categories/:id' => 'categories#show', :as => :show_category, :id=>/\d+/

  post '/categories/create' => 'categories#create', :as => :create_category
  post '/categories/update' => 'categories#update', :as => :update_category

  get '/sub-categories/:id' => 'sub_categories#show', :as => :show_sub_category, :id=>/\d+/

  post '/sub-categories/create' => 'sub_categories#create', :as => :create_sub_category
  post '/sub-categories/update' => 'sub_categories#update', :as => :update_sub_category

  get '/articles/:id' => 'articles#show', :as => :show_article, :id=>/\d+/

  post '/articles/create' => 'articles#create', :as => :create_article
  post '/articles/update' => 'articles#update', :as => :update_article

  get '/tags/:id' => 'tags#show', :as => :show_tag, :id=>/\d+/

  post '/tags/create' => 'tags#create', :as => :create_tag
  post '/tags/update' => 'tags#update', :as => :update_tag

  resources :articles, :categories, :sub_categories, :tags

  get ':id' => 'home#tiny_url', :article_id => /\d+/, :as => :tiny_url

end

app/models/tag.rb
class Tag < ActiveRecord::Base

  class << self
    include ApplicationHelper
  end

  has_and_belongs_to_many :articles

  validates :name, presence: true

  scope :by_active, -> {where('status = ?', true)}
  scope :by_favs, -> {where('favourite = ?', true)}
  scope :latest_by_updated, -> { order("updated_at desc") }

  def self.top_by_count
    self.all.sort{|x,y| y.articles.count <=> x.articles.count}
  end

  def self.get_favourites
    fetch_values(Tag.by_favs.first(6), "url_helpers.show_tag_path(y.id)")
  end

  def self.get_toppers
    fetch_values(Tag.top_by_count.first(6), "url_helpers.show_tag_path(y.id)")
  end

  def self.get_search(value)
    tag=Tag.where("name LIKE ?", "%#{value}%")
    fetch_values(tag, "url_helpers.show_tag_path(y.id)")
  end

  def articles_count
    self.articles.count rescue 0
  end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  def index
    @page_properties={:header => "Tags"}
    @tag = Tag.all #.where(:status => true)
  end

  def show
    @tag = Tag.find_by_id(params[:id])
    @page_properties={:header => @tag.try(:name).to_s.upcase}
    @articles = @tag.articles
  end

  def new
    @page_properties={:header => "New Tag"}
    @tag = Tag.new
  end

  def edit
    @page_properties={:header => "Edit Tag"}
    @tag = Tag.find(params[:id])
  end

  def create
    @tag = Tag.new(tag_params)
    if @tag.save
      redirect_to tags_path
    else
      render 'new'
    end
  end

  def update
    @tag = Tag.find(params[:id])
    if @tag.update(tag_params)
      redirect_to tags_path
    else
      render 'edit'
    end
  end

  private

  def tag_params
    params.require(:tag).permit(:name, :alias_name, :status, :favourite)
  end
  
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/_form.html.erb
<div class="wrapper">
  <div class="heading">
    <h3><%= @page_properties[:header] %></h3>
  </div>

  <% @breadcrumb = {:Home => root_path, :Tag => tags_path } %>
  <% @tag.new_record? ? (@breadcrumb[:New] = "#") : (@breadcrumb[@tag.name]=show_tag_path(@tag.id); @breadcrumb[:Edit] = "#") %>

  <%= render :partial => 'layouts/bread_crumb'%>

  <%= form_for @tag, method: :post, :url => @tag.new_record? ? :create_tag : :update_tag do |f| %>
      <div class="form_container_right settings">
        <div class="form_element">
          <%= f.label :Name %>
          <%= f.text_field :name, class: 'form_field' %>
        </div>

        <%= hidden_field_tag :id, @tag.id %>

        <div class="form_element">
          <%= f.label :Alias_Name %>
          <%= f.text_field :alias_name, class: 'form_field' %>
        </div>

        <div class="form_element check_box">
          <label>Status</label>
          <%= custom_check_box_1("tag[status]", true, @tag.status, "tag_status") %>
        </div>

        <div class="form_element check_box">
          <label>Make Favourite</label>
          <%= custom_check_box_1("tag[favourite]", true, @tag.favourite, "tag_favourite") %>
        </div>

        <div class="submit_div">
          <%#= f.submit :submit %>
          <%= custom_submit_1("Submit", nil, "right")%>
        </div>
      </div>
  <% end %>

  <% @mandatory_field = ['name','description'].to_json %>
  <% @attach_field = ['tag_'].to_json %>

  <%= render :partial => 'layouts/jquery_validation' %>
</div>

app/views/tags/_tags_block.html.erb
<%if @tag.present?%>
    <div class="index" align="center">
      <% @tag.each do |a| %>
          <%# debugger %>
          <a href="<%= show_tag_path(a.id.to_s) %>">
            <div class="article">
              <div class="head">
                <div class="title">
                  <h3><%= a.name %></h3>
                  <h6><%= a.alias_name %></h6>
                </div>
                <div class="count">
              <span>
                <%= a.articles_count %>
              </span>
                  <p><%= a.articles_count!=1 ? "Article".pluralize : "Article".singularize %></p>
                </div>
              </div>
            </div>
          </a>
      <% end %>
    </div>
<%else%>
    <div class="index" align="center">
      <h4>No Data to Display</h4>
    </div>
<%end%>

app/views/tags/edit.html.erb
<%= render 'form' %>

app/views/tags/index.html.erb
<div class="wrapper">
  <div class="heading">
    <h3><%= @page_properties[:header]%></h3>
    <%= custom_button_1("New Tag", new_tag_path, "right") %>
  </div>

  <% @breadcrumb ={:Home => root_path, :Tag => "#"} %>
  <%= render :partial => 'layouts/bread_crumb' %>

  <%= render :partial => 'tags/tags_block' %>
</div>

app/views/tags/new.html.erb
<%= render 'form' %>

app/views/tags/show.html.erb
<div class="wrapper">
  <div class="heading">
    <h3><%= @page_properties[:header]%></h3>

    <div class="fav <%= @tag.favourite ? "already-fav" : "make-fav" %>" data-url="Tag" data-id="<%= @tag.id %>"></div>
    <%#= custom_button_1("New A", new_sub_category_path, "right") %>
    <%= custom_button_2("Edit Tag", edit_tag_path(@tag.id), "right") %>

  </div>

  <% @breadcrumb ={:Home => root_path, :tags => tags_path, @tag.name => "#"}%>
  <%= render :partial => 'layouts/bread_crumb'%>

  <%= render :partial => 'articles/articles_block' %>
</div>