config/routes.rb
Rails.application.routes.draw do

  get 'tags/index'

  get 'home/dashboard' => 'home#dashboard'
  root 'home#dashboard'

  get '/get_favourites' => 'home#get_favs'
  get '/get_toppers' => 'home#get_toppers'
  post '/get_search' => 'home#get_search'
  get '/make_favourite' => 'home#make_favourite'
  get '/make_rating' => 'home#make_rating'

  get '/categories/:id' => 'categories#show', :as => :show_category, :id=>/\d+/

  post '/categories/create' => 'categories#create', :as => :create_category
  post '/categories/update' => 'categories#update', :as => :update_category

  get '/sub-categories/:id' => 'sub_categories#show', :as => :show_sub_category, :id=>/\d+/

  post '/sub-categories/create' => 'sub_categories#create', :as => :create_sub_category
  post '/sub-categories/update' => 'sub_categories#update', :as => :update_sub_category

  get '/articles/:id' => 'articles#show', :as => :show_article, :id=>/\d+/

  post '/articles/create' => 'articles#create', :as => :create_article
  post '/articles/update' => 'articles#update', :as => :update_article

  get '/tags/:id' => 'tags#show', :as => :show_tag, :id=>/\d+/

  post '/tags/create' => 'tags#create', :as => :create_tag
  post '/tags/update' => 'tags#update', :as => :update_tag

  resources :articles, :categories, :sub_categories, :tags

  get ':id' => 'home#tiny_url', :article_id => /\d+/, :as => :tiny_url

end

app/models/sub_category.rb
class SubCategory < ActiveRecord::Base

  class << self
    include ApplicationHelper
  end

  has_many :articles
  belongs_to :category

  validates :name, presence: true
  validates :description, presence: true

  scope :by_active, -> {where('status = ?', true)}
  scope :by_favs, -> {where('favourite = ?', true)}
  scope :latest_by_updated, -> { order("updated_at desc") }

  def self.top_by_count
    self.all.sort{|x,y| y.articles.count <=> x.articles.count}
  end

  def self.get_favourites
    fetch_values(SubCategory.by_favs.first(6), "url_helpers.show_sub_category_path(y.id)")
  end

  def self.get_toppers
    fetch_values(SubCategory.top_by_count.first(6), "url_helpers.show_sub_category_path(y.id)")
  end

  def self.get_search(value)
    sub_category=SubCategory.where("name LIKE ? OR description LIKE ?", "%#{value}%", "%#{value}%").uniq
    fetch_values(sub_category, "url_helpers.show_sub_category_path(y.id)")
  end

end

app/controllers/sub_categories_controller.rb
class SubCategoriesController < ApplicationController

  def index
    @page_properties={:header => "Sub Category"}
    @sub_category = SubCategory.all
  end

  def show
    @sub_category = SubCategory.find_by_id(params[:id])
    @page_properties={:header => @sub_category.try(:name).to_s.upcase}
    @articles = @sub_category.articles
  end

  def new
    @page_properties={:header => "New Sub Category"}
    @sub_category = SubCategory.new
  end

  def edit
    @page_properties={:header => "Edit Sub Category"}
    @sub_category = SubCategory.find(params[:id])
  end

  def create
    @sub_category = SubCategory.new(sub_category_params)
    if @sub_category.save
      redirect_to sub_categories_path
    else
      render 'new'
    end
  end

  def update
    @sub_category = SubCategory.find(params[:id])
    if @sub_category.update(sub_category_params)
      redirect_to sub_categories_path
    else
      render 'edit'
    end
  end

  def destroy

  end

  private

  def sub_category_params
    params.require(:sub_category).permit(:id, :name, :description, :status, :category_id, :favourite)
  end

end

app/views/sub_categories/_form.html.erb
<div class="wrapper">
  <div class="heading">
    <h3><%= @page_properties[:header]%></h3>
  </div>

  <% @breadcrumb = {:Home => root_path, :Sub_Category => sub_categories_path} %>
  <% @sub_category.new_record? ? (@breadcrumb[:New] = "#") : (@breadcrumb[@sub_category.name] = show_sub_category_path(@sub_category.id); @breadcrumb[:Edit]="#") %>
  <%= render :partial => 'layouts/bread_crumb' %>

  <%= form_for @sub_category, method: :post, :url => @sub_category.new_record? ? :create_sub_category : :update_sub_category do |f| %>
      <div class="form_container_right">
        <div class="form_element">
          <%= f.label :Name %>
          <%= f.text_field :name, class: 'form_field' %>
        </div>
        <div class="form_element">
          <%= f.label :Description %>
          <%= f.text_field :description, class: 'form_field' %>
        </div>
        <div class="form_element">
          <%= f.label :Category%>
          <%= collection_select :sub_category, :category_id, Category.all, :id, :name, options={:selected => @sub_category.category.try(:id), :include_blank => '--Select Category--'}, {:class=>"cs-select cs-skin-elastic"} %>
        </div>
        <div class="form_element check_box">
          <label>Status</label>
          <%= custom_check_box_1("sub_category[status]", true, @sub_category.status, "sub_category_status") %>
        </div>

        <div class="form_element check_box">
          <label>Make Favourite</label>
          <%= custom_check_box_1("sub_category[favourite]", true, @sub_category.favourite, "sub_category_favourite") %>
        </div>

        <%= hidden_field_tag :id, params[:id] %>

        <div class="submit_div">
          <%= custom_submit_1("Submit", nil, "right")%>
        </div>
      </div>
  <% end %>

  <% @mandatory_field = ['name','description'].to_json %>
  <% @attach_field = ['sub_category_'].to_json%>
  <%= render :partial => 'layouts/jquery_validation' %>
</div>

app/views/sub_categories/_sub_categories_block.html.erb
<%if @sub_category.present?%>
    <div class="index" align="center">
      <% @sub_category.each do |a| %>
          <a href="<%= show_sub_category_path(a.id.to_s) %>">
            <div class="article">
              <div class="head">
                <div class="title">
                  <h3><%= a.name %></h3>
                  <h6><%= a.description %></h6>
                </div>
                <div class="count">
          <span>
            <%= a.articles.count%>
          </span>
                  <p><%= a.articles.count!=1 ? "Articles".pluralize : "Articles".singularize %></p>
                </div>
              </div>
            </div>
          </a>
      <% end %>
    </div>
<%else%>
    <div class="index" align="center">
      <h4>No Data to Display</h4>
    </div>
<%end%>

app/views/sub_categories/index.html.erb
<div class="wrapper">
  <div class="heading">
    <h3><%= @page_properties[:header] %></h3>

    <%= custom_button_1("New Sub Category", new_sub_category_path, "right") %>
    <%#= custom_button_2("Edit Category", edit_category_path(@sub_category.category_id), "right") %>
  </div>

  <% @breadcrumb = {:Home => root_path, :Sub_Category => "#"} %>
  <%= render :partial => 'layouts/bread_crumb' %>

  <%= render :partial => 'sub_categories/sub_categories_block' %>
</div>

app/views/sub_categories/new.html.erb
<%= render 'form' %>

app/views/sub_categories/show.html.erb
<div class="wrapper">
  <div class="heading">
    <h3><%= @page_properties[:header]%></h3>
    <div class="fav <%= @sub_category.favourite ? "already-fav" : "make-fav" %>" data-url="SubCategory" data-id="<%= @sub_category.id %>"></div>

    <%= custom_button_1("New Article", new_article_path, "right") %>
    <%= custom_button_2("Edit Sub Category", edit_sub_category_path(@sub_category.id), "right") %>

  </div>

  <% @breadcrumb ={:Home => root_path, :categories => categories_path, @sub_category.category.name => show_category_path(@sub_category.category_id), @sub_category.name => "#"} %>
  <%= render :partial => 'layouts/bread_crumb'%>

  <%= render :partial => 'articles/articles_block' %>
</div>