config/routes.rb
Rails.application.routes.draw do

  get 'tags/index'

  get 'home/dashboard' => 'home#dashboard'
  root 'home#dashboard'

  get '/get_favourites' => 'home#get_favs'
  get '/get_toppers' => 'home#get_toppers'
  post '/get_search' => 'home#get_search'
  get '/make_favourite' => 'home#make_favourite'
  get '/make_rating' => 'home#make_rating'

  get '/categories/:id' => 'categories#show', :as => :show_category, :id=>/\d+/

  post '/categories/create' => 'categories#create', :as => :create_category
  post '/categories/update' => 'categories#update', :as => :update_category

  get '/sub-categories/:id' => 'sub_categories#show', :as => :show_sub_category, :id=>/\d+/

  post '/sub-categories/create' => 'sub_categories#create', :as => :create_sub_category
  post '/sub-categories/update' => 'sub_categories#update', :as => :update_sub_category

  get '/articles/:id' => 'articles#show', :as => :show_article, :id=>/\d+/

  post '/articles/create' => 'articles#create', :as => :create_article
  post '/articles/update' => 'articles#update', :as => :update_article

  get '/tags/:id' => 'tags#show', :as => :show_tag, :id=>/\d+/

  post '/tags/create' => 'tags#create', :as => :create_tag
  post '/tags/update' => 'tags#update', :as => :update_tag

  resources :articles, :categories, :sub_categories, :tags

  get ':id' => 'home#tiny_url', :article_id => /\d+/, :as => :tiny_url

end

app/views/layouts/_bread_crumb.html.erb
<div class="breadcrumbheader">
  <ul class="breadcrumbs">
     <% @breadcrumb.each do |key,val| %>
        <% if val!="#" %>
            <li><a href="<%= val %>"><%= key.to_s.gsub('_',' ').titlecase %></a></li>
        <% else %>
            <li><span><%= key.to_s.gsub('_',' ').titlecase %></span></li>
        <% end %>
     <% end %>
  </ul>
</div>

app/views/layouts/_jquery_validation.html.erb
<style>
    .error_label{
        color:orangered;
    }
    .error_field{
        border:1px solid red;
    }
</style>
<script>
    /*$($('div').find("input[type=submit]")).click(function(e){
        $( "input" ).each(function( ) {
            $('div').find("input[type=text]").each(function(){
                var value=$(this).val();
                if (!value){
                    e.preventDefault();
                    $(this).addClass('error_field');
                    $(this).prev().addClass('error_label');
                }
                else{
                    $(this).removeClass('error_field');
                    $(this).prev().removeClass('error_label');
                }
            });
        });
    });*/

    $($('div').find("input[type=submit]")).click(function(e){

        var value=0;
        var array = JSON.parse('<%= raw @mandatory_field %>');
        var field = JSON.parse('<%= raw @attach_field %>');
        var a=[];
        $.each(array, function( index, value ) {
            a.push(field[0] + value );
        });
        $('div').find("label").each(function(){
            var asd = $(this).next().attr('id');
            var flag = ($.inArray(asd, a));
            flag+=1;
            if (flag)
            {
                var chec = $('#'+asd).val();
                if ( chec=='' || chec == null)
                {
                    $('#'+asd).addClass('error_field');
                    $('#'+asd).prev().addClass('error_label');
                    value=1;
                }
                else{
                    $('#'+asd).removeClass('error_field');
                    $('#'+asd).prev().removeClass('error_label');
                    console.log("*******");
                }
            }
        });
        console.log(value);
        if (value){
            e.preventDefault();
        }
    });

</script>

app/views/layouts/_menu.html.erb
<style>
    menu > ul {
        margin: 0px;
        float: right;
    }
    li{
        font-size: 25px;
    }
    menu > ul > li {
        display:inline;
        padding:0px 10px;
    }
    menu > ul > li:hover a{
        border-bottom: 2px solid cornflowerblue;
        color: cornflowerblue;
    }
    .menu_anchor{
        padding: 15px 0px;
    }
</style>

<% role = "" %>
<% control = "" %>
<% if @current_user.present? %>
    <% role = "both" %>
    <% control = "admin"  if @current_user.role == "admin"  %>
<% end %>

<table style="width: 100%">
  <tbody>
  <tr>
    <!--<td style="width: 30%"><h1>My Site</h1></td>-->
    <td style="width: 70%">
      <menu>
        <ul>
          <% menu = Menu.where(access: ['all', role, control]).where(parent_id: 0) %>
          <% if menu.present? %>
              <% menu.order("sequence_number").each do |lists| %>
                  <li>
                    <%= link_to lists.title,{ :controller => lists.controller, :action => lists.action},{ :class => "menu_anchor"} %>
                    <% id = lists.id %>
                    <% submenu = Menu.where(parent_id: id )%>
                    <% if submenu.present? %>
                        <% submenu.order("sequence_number").each do |sublists| %>
                            <ul>
                              <li>
                                <%= link_to sublists.title, :controller => sublists.controller, :action => sublists.action %>
                              </li>
                            </ul>
                        <% end %>
                    <% end %>
                  </li>
              <% end %>
          <% end %>
        </ul>
      </menu>
    </td>
  </tr>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @page_properties[:page_title] %></title>

  <meta charset="UTF-8">
  <meta name="apple-mobile-web-app-capable" content="yes"/>
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />
  <meta name="google-site-verification" content="Bi9RrRAR7drDCVv1gcXbP1Ge0CrSPilZfJn7lpjWg88" />
  <meta name="viewport" content="width=device-width,initial-scale=1.0,maximum-scale=2.0,minimum-scale=1.0" />

  <%= csrf_meta_tags %>

  <link href='https://fonts.googleapis.com/css?family=Roboto+Condensed' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.2/jquery.min.js"></script>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

</head>
<body>
<div id="wrapper" class="toggled">
  <div id="sidebar-wrapper">
    <a id="menu-toggle" href="#menu-toggle"><span></span><span></span><span></span></a>
    <ul class="sidebar-nav">

      <%= direct_link_menu("Home", "/", "fa-home") %>
      <%= parent_with_submenu("Categories", "fa-th-large", {"New Category"=>new_category_path, "List Category"=>categories_path}) %>
      <%= parent_with_submenu("Sub Categories", "fa-th-list", {"New Sub Category"=>new_sub_category_path, "List Sub Category"=>sub_categories_path}) %>
      <%= direct_link_menu("Tags", "/tags", "fa-tag") %>
      <%= direct_link_menu("Articles", "/articles", "fa-book") %>

      <!-- direct link menu -->
      <!--<li><a href="/sub-categories"><i class="fa fa-home" aria-hidden="true"></i>Sub Categories</a></li>-->

      <!-- parent with submenu -->
      <!--<li><a href="#" class="sub-menu-toggle"><i class="fa fa-home" aria-hidden="true"></i><span>Sub Categories</span></a>
        <ul class="second-level-menu">
          <li><a href="#">New Sub Category</a></li>
          <li><a href="#">List Sub Category</a></li>
        </ul>
      </li>-->

    </ul>
  </div>
  <div id="page-content-wrapper">
    <div class="container-fluid no-padding">
      <header>
        <div class="top-menu">
          <ul class="no-margin">
            <% @categories.each do |cat| %>
                <li>
                  <a href="<%= show_category_path(cat.id) %>">
                    <%= cat.name %>
                  </a>
                </li>
            <% end %>
          </ul>
        </div>
      </header>

      <!--<div class="main-menu">
        <ul class="menu">
          <li><a href="#"><i class="fa fa-home" aria-hidden="true"></i><span>Home</span></a></li>
          <li><a href="#"><i class="fa fa-search" aria-hidden="true"></i><span>Categories</span></a></li>
          <li><a href="#"><i class="fa fa-search" aria-hidden="true"></i><span>Sub Categories</span></a></li>
          <li><a href="#"><i class="fa fa-tags" aria-hidden="true"></i><span>Tags</span></a></li>
          <li><a href="#"><i class="fa fa-book" aria-hidden="true"></i><span>Documents</span></a></li>
          <li><a href="#"><i class="fa fa-search" aria-hidden="true"></i><span>More</span></a></li>
        </ul>
      </div>-->

      <%#= render 'layouts/menu' %>

      <%= yield %>
    </div>
  </div>
</div>
<script>
    // select box script
    (function () {
        [].slice.call(document.querySelectorAll('select.cs-select')).forEach(function (el) {
            new SelectFx(el);
        });
    })();
</script>
</body>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js">
</html>